### ISSUE TITLE
Error in exiting

### ISSUE THREAD

**Issue by newinthegame** [VishuMallela/Monopoly1.0#1]
This is not actually an error more of a lacking feature.
You can not exit the game at all times, only at certain screens. I imagine this is one of the limitations of QBASIC which I'm pretty sure doesn't support multi-threading.

Kudos to you for this program! 
How long did it take to write the code?

**Comment by VishuMallela** [comment]
newinthegame,Thanks a lot for trying out my project! There is no multi-threading feature in QBasic as you mentioned. However, I will keep my eyes and ears open for an alternative that might fix the in-game exitting issue. I took me a good month to make this. Glad you like it!-VishuMallelaOn Mar 27, 2017 9:57 PM, newinthegame <notifications@github.com> wrote:This is not actually an error more of a lacking feature.
You can not exit the game at all times, only at certain screens. I imagine this is one of the limitations of QBASIC which I'm pretty sure doesn't support multi-threading.
Kudos to you for this program!
How long did it take to write the code?

**Comment by VishuMallela** [comment]
This issue in Monopoly1.0 will not have an effect on your gameplay. However, you cannot save your progress and exit the game at all times.
